global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sample-app'
    static_configs:
      - targets: ['sample-app:8000']
    metrics_path: /metrics

  - job_name: 'aether-agent'
    static_configs:
      - targets: ['aether-agent:8889']
    metrics_path: /metrics
